### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sinikala** [millalin/ot-harjoitustyo#1]
(Projekti ladattu koodikatselmointia varten 21.4. klo 18.49)

**Palautetta Tamagotchi-sovellukselle:**

Sovelluksesi on rakennettu erittäin selkeästi ja noudattaa mielestäni hienosti hyviä käytänteitä.
Eritoten ui-luokkasi on rakennettu  näppärästi; luokat ovat siistejä ja sovelluksen toiminta on helppo hahmottaa. Nappien eristäminen omaan luokkaansa edesauttaa luettavuutta.

Pakkausrakenne on kaikin puolin selkeä ja looginen. Metodit ja muuttujat on nimetty selkästi ja kuvaavasti.

**Muutamia kehitys-/korjausehdotuksia:**

Buttons-luokassa, jos haluaa säästää rivejä (esim rivi 83-86), kaikki napit voi lisätä kerralla komennolla:
`buttons2.getChildren().addAll(child1, child2,...);`

Muutama testimetodi on nimetty suomeksi, samoin TamagotchiDao-luokan `alustaTietokanta()`. Korjaathan ne ennen loppupalautusta.

Testeissä testi `tamagotchinNalkaOnAlussa700000` tuntuu testaavan pelkästään Tamagotchi-luokan toimintaa. Se olisi hyvä sijoittaa omaan Tamagotchi-luokan toimintaa testavaan testiluokkaan (TamagotchiTest).

Testipaketissakaan ei liene suotavaa olla default-packagea, testipaketit voisi nimetä testattavien pakettien mukaan (esim domainTest ?). Testiluokkien/-pakettien rakenteen olisi hyvä heijastaa varsinaisia paketteja/luokkia.

Tamagotchi-luokan metodi `loadTamagotchi` on varsin pitkä. Voisiko sitä jotenkin pilkkoa vastaamaan kurssin laatuvaatimuksia? Esim. Tamagotchin statistiikkojen päivitys omaksi metodikseen?

Kaiken kaikkiaan hyvää työtä ja onnea viimeistelyyn!

**Comment by millalin** [comment]
Kiitos hyvästä palautteesta! Osan asioista olinkin ehtinyt jo korjata! Katson ehdottomasti myös nuo muut kuntoon!
